# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ecoacoustics.info
subtitle: Community created ecoacoustics knowledgebase
author: the ecoacoustics community
description: >
  A community governed, curated, open source, knowledgebase 
  for all things related to ecoacoustics, soundscapes, and bioacoustics.
  Join us in adding new content!
logo: /assets/favico.png

# the subpath of your site, e.g. /blog
baseurl: ""

# the base hostname & protocol for your site, e.g. http://example.com
url: "https://ecoacoustics.info"

# integrations
google_analytics: #UA-NNNNNNNN-N
twitter_username: # e.g. atruskie
github_username: ecoacoustics
repository: ecoacoustics/ecoacoustics

# collections
collections:
  research_groups:
    output: true
    title: "Research Groups"
  societies:
    output: true
    title: "Societies"
  hardware:
    output: true
    title: "Hardware"
  software_packages:
    output: true
    title: "Software"
  applications:
    output: true
    title: "Applications"
  deployment:
    output: true
    title: "Deployment"
  literature:
    output: true
    title: "Literature"
  sound_analysis:
    output: true
    title: Analysis Techniques
  indices:
    output: true
    title: Indices
  recognisers:
    output: true
    title: Recognisers
  posts:
    output: true
    title: Blog Posts


# defaults
defaults: []



# Build settings
plugins_dir:  _jekyll/_plugins
layouts_dir:  _jekyll/_layouts
data_dir:     _jekyll/_data
includes_dir: _jekyll/_includes

permalink: pretty

markdown: kramdown

scholar:
  style: ./_bibliography/apa.csl
  source: ./_bibliography
  bibliography: references
  sort_by: year,month
  order: descending

liquid:
  error_mode: strict

plugins:
  - jekyll-feed
  - 'jekyll/scholar'
  - jekyll-assets
  - jekyll-github-metadata
  #- jekyll-last-modified-at
  - jekyll-git_metadata
exclude:
  - Gemfile
  - Gemfile.lock
  - .asset-cache
  - bin

# theme settings
# we're using no theme, but rather a custom theme now
theme: ~ 
date_format: "%F %T %:z"
time_format: "%FT%T:z"

# breadcrumbs
breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# assets (jekyll-assets)
assets:
  sources:
    - _jekyll/_assets/css
    - _jekyll/_assets/images
    - _jekyll/_assets/javascripts
    - _jekyll/_assets/stylesheets
    - _jekyll/_assets/fonts
    - _jekyll/_assets/img
    - _jekyll/_assets/js


# our own handrolled vendor asset management
# assumes all vendor assets come from the cloud
vendor_assets:
  font-awesome:
    sources:
      - url: https://use.fontawesome.com/72e1cdd251.js
  # bulma:
  #   sources: 
  #     - url: https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.3/css/bulma.css
  #       sri: sha256-iO7hYdKmrm9CzcGgNrUri6m9rA8CVi0qkG++7J6KlsM=
  #       env: development
  #     - url: https://cdnjs.cloudflare.com/ajax/libs/bulma/0.4.3/css/bulma.min.css
  #       sri: sha256-VC9bpAao257nf22leBRLU7AqKGwS9/Ylz8hfpHmOob4=
  #       env: production
  katex:
    sources:
      - url: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.js
        sri: sha256-gNVpJCw01Tg4rruvtWJp9vS0rRchXP2YF+U+b2lp8Po=
      - url: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css
        sri: sha256-tkzDFSl16wERzhCWg0ge2tON2+D6Qe9iEaJqM4ZGd4E=


